APT::FTPArchive::Release {
  Origin "frisky-gh-repo";
  Label "frisky-gh-repo";
  Suite "stable";
  Codename "stable";
  Architectures "all";
  Components "main";
  Description "apt repository by frisky-gh";
};
